# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

libgdalcubes_is_null <- function(pointer) {
    .Call('_gdalcubes_libgdalcubes_is_null', PACKAGE = 'gdalcubes', pointer)
}

libgdalcubes_version <- function() {
    .Call('_gdalcubes_libgdalcubes_version', PACKAGE = 'gdalcubes')
}

libgdalcubes_init <- function() {
    invisible(.Call('_gdalcubes_libgdalcubes_init', PACKAGE = 'gdalcubes'))
}

libgdalcubes_cleanup <- function() {
    invisible(.Call('_gdalcubes_libgdalcubes_cleanup', PACKAGE = 'gdalcubes'))
}

libgdalcubes_datetime_values <- function(pin) {
    .Call('_gdalcubes_libgdalcubes_datetime_values', PACKAGE = 'gdalcubes', pin)
}

libgdalcubes_cube_info <- function(pin) {
    .Call('_gdalcubes_libgdalcubes_cube_info', PACKAGE = 'gdalcubes', pin)
}

libgdalcubes_get_cube_view <- function(pin) {
    .Call('_gdalcubes_libgdalcubes_get_cube_view', PACKAGE = 'gdalcubes', pin)
}

libgdalcubes_update_cube_view <- function(pin, v) {
    invisible(.Call('_gdalcubes_libgdalcubes_update_cube_view', PACKAGE = 'gdalcubes', pin, v))
}

libgdalcubes_open_image_collection <- function(filename) {
    .Call('_gdalcubes_libgdalcubes_open_image_collection', PACKAGE = 'gdalcubes', filename)
}

libgdalcubes_image_collection_info <- function(pin) {
    .Call('_gdalcubes_libgdalcubes_image_collection_info', PACKAGE = 'gdalcubes', pin)
}

libgdalcubes_create_image_collection <- function(files, format_file, outfile, unroll_archives = TRUE) {
    .Call('_gdalcubes_libgdalcubes_create_image_collection', PACKAGE = 'gdalcubes', files, format_file, outfile, unroll_archives)
}

libgdalcubes_list_collection_formats <- function() {
    .Call('_gdalcubes_libgdalcubes_list_collection_formats', PACKAGE = 'gdalcubes')
}

libgdalcubes_create_image_collection_cube <- function(pin, chunk_sizes, v = NULL) {
    .Call('_gdalcubes_libgdalcubes_create_image_collection_cube', PACKAGE = 'gdalcubes', pin, chunk_sizes, v)
}

libgdalcubes_create_reduce_cube <- function(pin, reducer) {
    .Call('_gdalcubes_libgdalcubes_create_reduce_cube', PACKAGE = 'gdalcubes', pin, reducer)
}

libgdalcubes_create_join_bands_cube <- function(pinA, pinB) {
    .Call('_gdalcubes_libgdalcubes_create_join_bands_cube', PACKAGE = 'gdalcubes', pinA, pinB)
}

libgdalcubes_create_select_bands_cube <- function(pin, bands) {
    .Call('_gdalcubes_libgdalcubes_create_select_bands_cube', PACKAGE = 'gdalcubes', pin, bands)
}

libgdalcubes_create_apply_pixel_cube <- function(pin, expr, names) {
    .Call('_gdalcubes_libgdalcubes_create_apply_pixel_cube', PACKAGE = 'gdalcubes', pin, expr, names)
}

libgdalcubes_debug_output <- function(debug) {
    invisible(.Call('_gdalcubes_libgdalcubes_debug_output', PACKAGE = 'gdalcubes', debug))
}

libgdalcubes_eval_cube <- function(pin, outfile) {
    invisible(.Call('_gdalcubes_libgdalcubes_eval_cube', PACKAGE = 'gdalcubes', pin, outfile))
}

libgdalcubes_create_stream_cube <- function(pin, cmd) {
    .Call('_gdalcubes_libgdalcubes_create_stream_cube', PACKAGE = 'gdalcubes', pin, cmd)
}

libgdalcubes_set_threads <- function(n) {
    invisible(.Call('_gdalcubes_libgdalcubes_set_threads', PACKAGE = 'gdalcubes', n))
}

