# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gc_is_null <- function(pointer) {
    .Call('_gdalcubes_gc_is_null', PACKAGE = 'gdalcubes', pointer)
}

gc_version <- function() {
    .Call('_gdalcubes_gc_version', PACKAGE = 'gdalcubes')
}

gc_gdalformats <- function() {
    .Call('_gdalcubes_gc_gdalformats', PACKAGE = 'gdalcubes')
}

gc_set_gdal_config <- function(k, v) {
    invisible(.Call('_gdalcubes_gc_set_gdal_config', PACKAGE = 'gdalcubes', k, v))
}

gc_set_streamining_dir <- function(dir) {
    invisible(.Call('_gdalcubes_gc_set_streamining_dir', PACKAGE = 'gdalcubes', dir))
}

gc_gdalversion <- function() {
    .Call('_gdalcubes_gc_gdalversion', PACKAGE = 'gdalcubes')
}

gc_gdal_has_geos <- function() {
    .Call('_gdalcubes_gc_gdal_has_geos', PACKAGE = 'gdalcubes')
}

gc_add_format_dir <- function(dir) {
    invisible(.Call('_gdalcubes_gc_add_format_dir', PACKAGE = 'gdalcubes', dir))
}

gc_init <- function() {
    invisible(.Call('_gdalcubes_gc_init', PACKAGE = 'gdalcubes'))
}

gc_cleanup <- function() {
    invisible(.Call('_gdalcubes_gc_cleanup', PACKAGE = 'gdalcubes'))
}

gc_datetime_values <- function(pin) {
    .Call('_gdalcubes_gc_datetime_values', PACKAGE = 'gdalcubes', pin)
}

gc_cube_info <- function(pin) {
    .Call('_gdalcubes_gc_cube_info', PACKAGE = 'gdalcubes', pin)
}

gc_dimension_values_from_view <- function(view, dt_unit = "") {
    .Call('_gdalcubes_gc_dimension_values_from_view', PACKAGE = 'gdalcubes', view, dt_unit)
}

gc_dimension_bounds <- function(pin, dt_unit = "") {
    .Call('_gdalcubes_gc_dimension_bounds', PACKAGE = 'gdalcubes', pin, dt_unit)
}

gc_dimension_values <- function(pin, dt_unit = "") {
    .Call('_gdalcubes_gc_dimension_values', PACKAGE = 'gdalcubes', pin, dt_unit)
}

gc_open_image_collection <- function(filename) {
    .Call('_gdalcubes_gc_open_image_collection', PACKAGE = 'gdalcubes', filename)
}

gc_image_collection_info <- function(pin) {
    .Call('_gdalcubes_gc_image_collection_info', PACKAGE = 'gdalcubes', pin)
}

gc_image_collection_extent <- function(pin, srs) {
    .Call('_gdalcubes_gc_image_collection_extent', PACKAGE = 'gdalcubes', pin, srs)
}

gc_create_image_collection_from_format <- function(files, format_file, outfile, unroll_archives = TRUE) {
    invisible(.Call('_gdalcubes_gc_create_image_collection_from_format', PACKAGE = 'gdalcubes', files, format_file, outfile, unroll_archives))
}

gc_create_image_collection_from_datetime <- function(outfile, files, date_time, use_subdatasets, band_names) {
    invisible(.Call('_gdalcubes_gc_create_image_collection_from_datetime', PACKAGE = 'gdalcubes', outfile, files, date_time, use_subdatasets, band_names))
}

gc_add_images <- function(pin, files, unroll_archives = TRUE, outfile = "") {
    invisible(.Call('_gdalcubes_gc_add_images', PACKAGE = 'gdalcubes', pin, files, unroll_archives, outfile))
}

gc_list_collection_formats <- function() {
    .Call('_gdalcubes_gc_list_collection_formats', PACKAGE = 'gdalcubes')
}

gc_create_view <- function(v) {
    .Call('_gdalcubes_gc_create_view', PACKAGE = 'gdalcubes', v)
}

gc_create_image_collection_cube <- function(pin, chunk_sizes, mask, v = NULL) {
    .Call('_gdalcubes_gc_create_image_collection_cube', PACKAGE = 'gdalcubes', pin, chunk_sizes, mask, v)
}

gc_create_ncdf_cube <- function(path, chunk_sizes, auto_unpack) {
    .Call('_gdalcubes_gc_create_ncdf_cube', PACKAGE = 'gdalcubes', path, chunk_sizes, auto_unpack)
}

gc_create_dummy_cube <- function(v, nbands, fill, chunk_sizes) {
    .Call('_gdalcubes_gc_create_dummy_cube', PACKAGE = 'gdalcubes', v, nbands, fill, chunk_sizes)
}

gc_create_empty_cube <- function(v, nbands, chunk_sizes) {
    .Call('_gdalcubes_gc_create_empty_cube', PACKAGE = 'gdalcubes', v, nbands, chunk_sizes)
}

gc_copy_cube <- function(pin) {
    .Call('_gdalcubes_gc_copy_cube', PACKAGE = 'gdalcubes', pin)
}

gc_from_json_file <- function(path) {
    .Call('_gdalcubes_gc_from_json_file', PACKAGE = 'gdalcubes', path)
}

gc_from_json_string <- function(json) {
    .Call('_gdalcubes_gc_from_json_string', PACKAGE = 'gdalcubes', json)
}

gc_create_rename_bands_cube <- function(pin, names_old, names_new) {
    .Call('_gdalcubes_gc_create_rename_bands_cube', PACKAGE = 'gdalcubes', pin, names_old, names_new)
}

gc_create_reduce_time_cube <- function(pin, reducers, bands) {
    .Call('_gdalcubes_gc_create_reduce_time_cube', PACKAGE = 'gdalcubes', pin, reducers, bands)
}

gc_create_stream_reduce_time_cube <- function(pin, cmd, nbands, names) {
    .Call('_gdalcubes_gc_create_stream_reduce_time_cube', PACKAGE = 'gdalcubes', pin, cmd, nbands, names)
}

gc_create_stream_reduce_space_cube <- function(pin, cmd, nbands, names) {
    .Call('_gdalcubes_gc_create_stream_reduce_space_cube', PACKAGE = 'gdalcubes', pin, cmd, nbands, names)
}

gc_create_reduce_space_cube <- function(pin, reducers, bands) {
    .Call('_gdalcubes_gc_create_reduce_space_cube', PACKAGE = 'gdalcubes', pin, reducers, bands)
}

gc_create_window_time_cube_reduce <- function(pin, window, reducers, bands) {
    .Call('_gdalcubes_gc_create_window_time_cube_reduce', PACKAGE = 'gdalcubes', pin, window, reducers, bands)
}

gc_create_window_time_cube_kernel <- function(pin, window, kernel) {
    .Call('_gdalcubes_gc_create_window_time_cube_kernel', PACKAGE = 'gdalcubes', pin, window, kernel)
}

gc_create_join_bands_cube <- function(pin_list, cube_names) {
    .Call('_gdalcubes_gc_create_join_bands_cube', PACKAGE = 'gdalcubes', pin_list, cube_names)
}

gc_create_select_bands_cube <- function(pin, bands) {
    .Call('_gdalcubes_gc_create_select_bands_cube', PACKAGE = 'gdalcubes', pin, bands)
}

gc_create_select_time_cube <- function(pin, t) {
    .Call('_gdalcubes_gc_create_select_time_cube', PACKAGE = 'gdalcubes', pin, t)
}

gc_create_apply_pixel_cube <- function(pin, expr, names, keep_bands = FALSE) {
    .Call('_gdalcubes_gc_create_apply_pixel_cube', PACKAGE = 'gdalcubes', pin, expr, names, keep_bands)
}

gc_create_stream_apply_pixel_cube <- function(pin, cmd, nbands, names, keep_bands = FALSE) {
    .Call('_gdalcubes_gc_create_stream_apply_pixel_cube', PACKAGE = 'gdalcubes', pin, cmd, nbands, names, keep_bands)
}

gc_create_stream_apply_time_cube <- function(pin, cmd, nbands, names, keep_bands = FALSE) {
    .Call('_gdalcubes_gc_create_stream_apply_time_cube', PACKAGE = 'gdalcubes', pin, cmd, nbands, names, keep_bands)
}

gc_create_filter_predicate_cube <- function(pin, pred) {
    .Call('_gdalcubes_gc_create_filter_predicate_cube', PACKAGE = 'gdalcubes', pin, pred)
}

gc_create_filter_geom_cube <- function(pin, wkt, srs) {
    .Call('_gdalcubes_gc_create_filter_geom_cube', PACKAGE = 'gdalcubes', pin, wkt, srs)
}

gc_set_err_handler <- function(debug, log_to_file = "") {
    invisible(.Call('_gdalcubes_gc_set_err_handler', PACKAGE = 'gdalcubes', debug, log_to_file))
}

gc_eval_cube <- function(pin, outfile, compression_level = 0L, with_VRT = FALSE, write_bounds = TRUE, packing = NULL) {
    invisible(.Call('_gdalcubes_gc_eval_cube', PACKAGE = 'gdalcubes', pin, outfile, compression_level, with_VRT, write_bounds, packing))
}

gc_write_chunks_ncdf <- function(pin, dir, name, compression_level = 0L) {
    invisible(.Call('_gdalcubes_gc_write_chunks_ncdf', PACKAGE = 'gdalcubes', pin, dir, name, compression_level))
}

gc_write_tif <- function(pin, dir, prefix = "", overviews = FALSE, cog = FALSE, creation_options = NULL, rsmpl_overview = "nearest", packing = NULL) {
    invisible(.Call('_gdalcubes_gc_write_tif', PACKAGE = 'gdalcubes', pin, dir, prefix, overviews, cog, creation_options, rsmpl_overview, packing))
}

gc_create_stream_cube <- function(pin, cmd) {
    .Call('_gdalcubes_gc_create_stream_cube', PACKAGE = 'gdalcubes', pin, cmd)
}

gc_create_simple_cube <- function(files, datetime_values, bands, band_names, dx, dy, chunk_sizes) {
    .Call('_gdalcubes_gc_create_simple_cube', PACKAGE = 'gdalcubes', files, datetime_values, bands, band_names, dx, dy, chunk_sizes)
}

gc_create_fill_time_cube <- function(pin, method) {
    .Call('_gdalcubes_gc_create_fill_time_cube', PACKAGE = 'gdalcubes', pin, method)
}

gc_create_aggregate_time_cube <- function(pin, dt, method, fact = 0L) {
    .Call('_gdalcubes_gc_create_aggregate_time_cube', PACKAGE = 'gdalcubes', pin, dt, method, fact)
}

gc_create_slice_time_cube <- function(pin, dt, it = 0L) {
    .Call('_gdalcubes_gc_create_slice_time_cube', PACKAGE = 'gdalcubes', pin, dt, it)
}

gc_create_slice_space_cube <- function(pin, loc, i) {
    .Call('_gdalcubes_gc_create_slice_space_cube', PACKAGE = 'gdalcubes', pin, loc, i)
}

gc_create_crop_cube <- function(pin, extent, iextent, snap) {
    .Call('_gdalcubes_gc_create_crop_cube', PACKAGE = 'gdalcubes', pin, extent, iextent, snap)
}

gc_extract <- function(pin, ogr_dataset, time_column = "") {
    .Call('_gdalcubes_gc_extract', PACKAGE = 'gdalcubes', pin, ogr_dataset, time_column)
}

gc_exec_worker <- function(json_path, pid, nworker, work_dir, compression = 0L) {
    invisible(.Call('_gdalcubes_gc_exec_worker', PACKAGE = 'gdalcubes', json_path, pid, nworker, work_dir, compression))
}

gc_set_process_execution <- function(n_worker, cmd, debug, ncdf_compression_level, use_overviews, gdal_options) {
    invisible(.Call('_gdalcubes_gc_set_process_execution', PACKAGE = 'gdalcubes', n_worker, cmd, debug, ncdf_compression_level, use_overviews, gdal_options))
}

gc_set_progress <- function(show_progress) {
    invisible(.Call('_gdalcubes_gc_set_progress', PACKAGE = 'gdalcubes', show_progress))
}

gc_set_use_overviews <- function(use_overviews) {
    invisible(.Call('_gdalcubes_gc_set_use_overviews', PACKAGE = 'gdalcubes', use_overviews))
}

gc_detect_cores <- function() {
    .Call('_gdalcubes_gc_detect_cores', PACKAGE = 'gdalcubes')
}

gc_simple_hash <- function(instr) {
    .Call('_gdalcubes_gc_simple_hash', PACKAGE = 'gdalcubes', instr)
}

gc_create_stac_collection <- function(bands, images, gdalrefs, outfile, image_md) {
    invisible(.Call('_gdalcubes_gc_create_stac_collection', PACKAGE = 'gdalcubes', bands, images, gdalrefs, outfile, image_md))
}

